#!/usr/bin/env python3

import os
import click
from dotenv import load_dotenv


@click.command()
@click.argument("args", nargs=-1)
def run_command(args):
    load_dotenv()
    PROJECT_NAME = os.getenv("PROJECT_NAME","")
    database = "testing"
    container = "docker exec -uodoo -it " + PROJECT_NAME
    test_tags = "/binaural_accountant"

    modules = ["l10n_ve","binaural_rate","account","binaural_accountant"] 
    os.system(f"{container} odoo --test-tags {test_tags} -d {database} -i {','.join(modules)} --without-demo=True --stop-after-init -c /home/odoo/.config/odoo.conf")


if __name__ == "__main__":
    run_command()
